-- phpMyAdmin SQL Dump
-- version 5.2.2
-- https://www.phpmyadmin.net/
--
-- Hôte : mysql-server
-- Généré le : mar. 10 mars 2026 à 09:03
-- Version du serveur : 8.4.8
-- Version de PHP : 8.2.29

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `travelinseoul`
--

-- --------------------------------------------------------

--
-- Structure de la table `admins`
--

CREATE TABLE `admins` (
  `id` int NOT NULL,
  `username` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Déchargement des données de la table `admins`
--

INSERT INTO `admins` (`id`, `username`, `password`, `created_at`, `user_id`) VALUES
(1, 'remychalendard', '$2y$12$hfrJXssshuM5VNAxeqOnNuXymBpKL8qw.Nc3V3iSec3DeyFjNvNl2', '2026-03-05 16:58:43', NULL);

-- --------------------------------------------------------

--
-- Structure de la table `articles`
--

CREATE TABLE `articles` (
  `id` int NOT NULL,
  `titre` varchar(255) NOT NULL,
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `contenu` longtext NOT NULL,
  `auteur` varchar(100) DEFAULT NULL,
  `date_creation` datetime DEFAULT CURRENT_TIMESTAMP,
  `date_modification` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `image` varchar(255) DEFAULT NULL,
  `categorie` varchar(100) DEFAULT NULL,
  `statut` enum('brouillon','publie','archive') DEFAULT 'brouillon',
  `user_id` int DEFAULT NULL,
  `etat` varchar(20) DEFAULT 'publiée',
  `photo` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Déchargement des données de la table `articles`
--

INSERT INTO `articles` (`id`, `titre`, `description`, `contenu`, `auteur`, `date_creation`, `date_modification`, `image`, `categorie`, `statut`, `user_id`, `etat`, `photo`) VALUES
(1, 'Football - FC Seoul', 'Football, Seoul World Cup Stadium, Séoul', 'Le FC Seoul est l’un des clubs de football les plus emblématiques de Corée du Sud. Fondé en 1983 sous le nom de Lucky-Goldstar Hwangso FC, le club était initialement basé à Chungcheong avant de déménager dans la capitale, Séoul, en 1989. Au fil des années, il a changé de nom plusieurs fois, devenant LG Cheetahs, puis finalement FC Seoul en 2004. Le club joue ses matchs à domicile au Seoul World Cup Stadium, un stade moderne inauguré pour la Coupe du Monde 2002. Le FC Seoul a remporté plusieurs titres de K League 1, ainsi que des Coupes de Corée, et s’est souvent illustré sur la scène asiatique, notamment en Ligue des champions de l’AFC. Connu pour sa rivalité intense avec les Suwon Samsung Bluewings surnommée le « Super Match », le FC Seoul est aujourd’hui un pilier du football sud-coréen, reconnu pour son histoire riche, son large public et son style de jeu ambitieux.\r\n', 'Remy Chalendard', '2026-03-03 08:59:55', '2026-03-03 11:08:04', ' https://ichef.bbci.co.uk/ace/standard/1024/cpsprodpb/1469E/production/_133141638_lingard.jpg\r\n', 'Evenements', 'publie', NULL, 'publiée', NULL),
(2, 'Lotte World', 'Parc d\'attraction, 240 Olympic-ro, Songpa District, Seoul, Corée du Sud', 'Le Lotte World est l’un des parcs d’attractions les plus célèbres et les plus populaires de Séoul, en Corée du Sud. Inauguré en 1989, il se distingue par sa particularité d’être à la fois un parc intérieur le plus grand du monde et un parc extérieur, appelé Magic Island, construit autour d’un lac pittoresque. Situé dans le quartier de Jamsil, Lotte World offre une grande variété d’attractions, allant des montagnes russes aux spectacles culturels, en passant par des parades, des patinoires et un aquarium. Le complexe comprend également un centre commercial, un hôtel de luxe et un musée folklorique coréen, faisant de Lotte World une destination de loisirs complète pour les familles, les touristes et les amateurs de sensations fortes. Grâce à son atmosphère magique et à ses installations modernes, il est devenu un symbole du divertissement à Séoul et une étape incontournable pour les visiteurs de la capitale sud-coréenne.\r\n', 'Remy Chalendard', '2026-03-03 09:01:35', '2026-03-03 11:08:17', 'images/lotteworld.webp', 'Evenements', 'publie', NULL, 'publiée', NULL),
(3, 'K-POP, Un phénomène mondial', 'Divertissement', 'La K-pop, ou Korean pop music, est un genre musical originaire de Corée du Sud qui mélange des styles variés comme la pop, le hip-hop, le R&B, l’électro et même le rock. Elle est née dans les années 1990, avec des groupes pionniers comme Seo Taiji and Boys, qui ont introduit des sons occidentaux et des chorégraphies modernes dans la musique coréenne. Rapidement, les grandes agences de divertissement comme SM Entertainment, YG Entertainment et JYP Entertainment ont mis en place un système d’entraînement rigoureux pour former de jeunes artistes, appelés idols, à chanter, danser et se produire sur scène avec professionnalisme. La K-pop est devenue populaire dans le monde entier grâce à son esthétique soignée, ses clips spectaculaires, ses chorégraphies dynamiques et l’implication des fans sur les réseaux sociaux. Des groupes comme BLACKPINK, IVE ou Newjeans ont contribué à faire de la K-pop un phénomène mondial, symbole de la culture coréenne moderne et de la puissance du soft power sud-coréen.\r\n', 'Remy Chalendard', '2026-03-03 09:02:44', '2026-03-03 11:08:30', 'images/kpop.webp', 'Evenements', 'publie', NULL, 'publiée', NULL),
(4, 'Temple de Jogyesa', 'Monument, Adresse : 55 Ujeongguk-ro, Jongno-gu, Séoul', 'Le temple de Jogyesa est l\'un des temples bouddhistes les plus importants et les plus emblématiques de Séoul, situé au cœur du quartier historique de Jongno. Fondé en 1395, il a été réaménagé en 1910, et est aujourd’hui le centre principal du bouddhisme Jogye, la secte bouddhiste la plus influente en Corée du Sud. Ce temple est un lieu de prière, de méditation et de réflexion spirituelle, attirant à la fois les locaux et les visiteurs internationaux. L’atmosphère du temple est particulièrement sereine, et ses bâtiments traditionnels sont magnifiquement ornés. Le hall principal, le Daeungjeon, abrite une grande statue du Bouddha, entourée de peintures murales représentant des scènes bouddhiques. Une caractéristique unique de Jogyesa est son arbre de saule géant âgé de plusieurs siècles, un symbole de la sagesse et de la longévité dans le bouddhisme. En plus des structures religieuses, le temple dispose d\'un jardin paisible où les visiteurs peuvent se détendre et méditer.\r\n', 'Remy Chalendard', '2026-03-03 09:04:02', '2026-03-03 11:08:42', 'images/Jogyesa.webp', 'Evenements', 'publie', NULL, 'publiée', NULL),
(5, 'Daeungjeon Hall', 'Monument', 'L\'arbre de saule géant : vieux de plus de 500 ans, il symbolise la sagesse bouddhiste. Le pavillon de la méditation : où les moines et visiteurs peuvent pratiquer la méditation. Les lanternes de la paix : lors de certaines périodes, le temple est décoré de milliers de lanternes colorées, créant une ambiance spectaculaire. Le temple est également un lieu de grande importance culturelle, avec des événements comme le Buddha’s Birthday Festival (Fête de Bouddha) en avril ou mai, où des lanternes sont suspendues partout et des cérémonies sont organisées. La zone autour de Jogyesa est un mélange de culture traditionnelle et moderne, avec des cafés, des galeries d\'art et des boutiques artisanales, parfait pour une promenade après une visite spirituelle.\r\n', 'Remy Chalendard', '2026-03-03 09:05:26', '2026-03-03 11:08:55', 'images/hall-daeungjeon-temple-bulguksa-gyeongju-900x600.webp', 'Evenements', 'publie', NULL, 'publiée', NULL),
(6, 'Les quartiers populaires de Séoul', 'Gangnam', '  Gangnam est l’un des quartiers les plus célèbres et dynamiques de\r\n      Séoul, en Corée du Sud. Son nom signifie littéralement « au sud de\r\n      la rivière » (en référence à la rivière Han). C’est un symbole de\r\n      modernité, de richesse et de style de vie haut de gamme. Le quartier\r\n      est connu pour ses gratte-ciels élégants, ses centres commerciaux\r\n      luxueux et ses boutiques de créateurs. Il attire beaucoup de jeunes\r\n      professionnels, entrepreneurs et célébrités, ce qui lui donne une\r\n      atmosphère très cosmopolite et branchée. Gangnam n’est pas seulement\r\n      un lieu pour le shopping et la vie nocturne : c’est aussi un centre\r\n      d’affaires majeur, avec de nombreuses entreprises technologiques et\r\n      start-ups installées dans la région. Les rues sont animées par des\r\n      cafés à la mode, des restaurants sophistiqués et des clubs réputés.\r\n      Enfin, Gangnam a acquis une renommée mondiale grâce à la culture\r\n      populaire, notamment avec le tube “Gangnam Style”, qui a mis en\r\n      lumière ce quartier chic et ses habitants élégants et ambitieux. En\r\n      résumé, Gangnam est le quartier où modernité, richesse et culture\r\n      urbaine se rencontren\r\n\r\n      Quelques hôtels recommandés :\r\n    \r\n      Park Hyatt Seoul\r\n      Lotte Hotel Seoul\r\n      Shilla Stay Gangnam', 'Remy Chalendard', '2026-03-03 10:56:20', '2026-03-04 12:07:04', 'images/gangnam.webp', 'Quartiers', 'publie', NULL, 'publiée', NULL),
(7, 'Hongdae', '', '      Hongdae (contraction de Hongik Daehakgyo, l’Université Hongik) est\r\n      un quartier jeune, artistique et très animé situé dans l’ouest de\r\n      Séoul. Il est célèbre pour sa vie culturelle dynamique, sa scène\r\n      musicale alternative et son ambiance étudiante. Le quartier regorge\r\n      de cafés originaux, de bars et de restaurants tendance, mais c’est\r\n      surtout un haut lieu de la créativité et de l’art urbain : les rues\r\n      sont souvent décorées de graffitis colorés, et des performances de\r\n      rue ont lieu presque tous les jours, que ce soit de la musique, de\r\n      la danse ou du théâtre improvisé. Hongdae est aussi connu pour sa\r\n      vie nocturne effervescente : clubs, pubs et spectacles attirent de\r\n      nombreux jeunes locaux et touristes. Les marchés de rue du week-end,\r\n      comme le Hongdae Free Market, permettent de découvrir des créations\r\n      d’artistes et des objets faits main, ce qui renforce son côté\r\n      alternatif et bohème. En résumé, Hongdae est un quartier créatif,\r\n      énergique et jeune, parfait pour ceux qui veulent explorer la\r\n      culture contemporaine de Séoul et profiter d’une ambiance artistique\r\n      et festive.\r\n    \r\n      Quelques hôtels recommandés :\r\n    \r\n      RYSE, Autograph Collection\r\n      Amanti Hotel Seoul\r\n      9 Brick Hotel', 'Remy Chalendard', '2026-03-03 10:59:44', '2026-03-04 12:07:04', 'images/hongdae.webp', 'Quartiers', 'publie', NULL, 'publiée', NULL),
(8, 'Insadong', '', '\r\n      Insadong est le quartier traditionnel et culturel de Séoul, situé\r\n      près du palais Gyeongbokgung. Contrairement à Gangnam ou Hongdae,\r\n      Insadong est réputé pour son atmosphère historique et authentique,\r\n      où l’on peut découvrir la culture coréenne classique. Les rues\r\n      d’Insadong sont bordées de boutiques d’artisanat, de galeries d’art,\r\n      de salons de thé traditionnels et de magasins d’antiquités. On y\r\n      trouve également des calligraphies, céramiques, peintures et\r\n      souvenirs artisanaux, parfaits pour ceux qui veulent rapporter un\r\n      morceau de culture coréenne. Le quartier est aussi un lieu où la\r\n      tradition rencontre la modernité : des cafés modernes et des\r\n      restaurants s’installent dans des bâtiments au style ancien, créant\r\n      une ambiance charmante et unique. Les week-ends, Insadong accueille\r\n      souvent des performances culturelles et des festivals traditionnels,\r\n      ce qui permet aux visiteurs de s’immerger dans le patrimoine coréen.\r\n      En résumé, Insadong est le quartier où le passé de Séoul se vit et\r\n      se découvre, idéal pour explorer l’art, l’artisanat et les\r\n      traditions coréennes dans une atmosphère calme et authentique.\r\n    \r\n      Quelques hôtels recommandés :\r\n    \r\n      Orakai Insadong Suites\r\n      Sunbee Hotel\r\n      Hotel Aventree Jongno', 'Remy Chalendard', '2026-03-03 11:01:38', '2026-03-03 11:06:30', 'images/insadong.webp', 'Quartiers', 'publie', NULL, 'publiée', NULL),
(9, 'Myeongdong', '', '  \r\n      Myeongdong est l’un des quartiers les plus dynamiques et commerciaux\r\n      de Séoul, connu pour être un véritable paradis du shopping et de la\r\n      mode. Situé en plein centre de la ville, il attire aussi bien les\r\n      touristes que les habitants. Les rues de Myeongdong sont remplies de\r\n      boutiques de vêtements, de cosmétiques, de chaussures et\r\n      d’accessoires, allant des grandes marques internationales aux\r\n      petites enseignes locales. C’est également un endroit réputé pour sa\r\n      cuisine de rue, où l’on peut goûter des snacks coréens populaires\r\n      comme les tteokbokki (gâteaux de riz épicés) ou les hotteok (crêpes\r\n      sucrées). Le quartier est animé du matin jusqu’au soir, avec des\r\n      lumières néon et des panneaux publicitaires colorés qui créent une\r\n      atmosphère électrique et moderne. Myeongdong est aussi un centre de\r\n      beauté et de soins, avec de nombreuses boutiques de cosmétiques et\r\n      de soins de la peau, reflet de la célèbre culture coréenne du\r\n      “K-beauty”. En résumé, Myeongdong est le quartier parfait pour le\r\n      shopping, la street food et l’effervescence urbaine, offrant une\r\n      expérience vibrante et moderne de Séoul.\r\n    \r\n      Quelques hôtels recommandés :\r\n    \r\n      Lotte Hotel Myeongdong\r\n      Nine Tree Hotel Myeongdong\r\n      Loisir Hotel Seoul Myeongdong', 'Remy Chalendard', '2026-03-03 11:03:00', '2026-03-03 11:03:00', 'images/myeongdong.webp', 'Quartiers', 'publie', NULL, 'publiée', NULL),
(10, 'Itaewon', '', '\r\n      Itaewon est le quartier multiculturel et cosmopolite de Séoul. Il\r\n      est célèbre pour sa diversité, accueillant des résidents et des\r\n      visiteurs du monde entier, ce qui en fait un lieu unique en Corée du\r\n      Sud. Le quartier est rempli de restaurants internationaux, proposant\r\n      des cuisines venues de presque tous les continents : turque,\r\n      indienne, mexicaine, italienne, et bien sûr coréenne. C’est aussi un\r\n      endroit où l’on trouve de nombreux bars, clubs et cafés, souvent\r\n      fréquentés par des expatriés et des touristes, donnant à Itaewon une\r\n      vie nocturne très animée et internationale. Itaewon est également\r\n      connu pour ses boutiques originales, marchés et magasins de\r\n      vêtements uniques, souvent plus excentriques ou alternatifs que dans\r\n      d’autres quartiers de Séoul. Il attire ceux qui recherchent une\r\n      ambiance internationale et ouverte, différente du style plus\r\n      traditionnel ou branché des autres quartiers. En résumé, Itaewon est\r\n      le quartier où les cultures se rencontrent, parfait pour découvrir\r\n      Séoul sous un angle cosmopolite, goûter des cuisines du monde et\r\n      profiter d’une atmosphère festive et multiculturelle.\r\n    \r\n      Quelques hôtels recommandés :\r\n    \r\n      Hamilton Hotel\r\n      Imperial Palace Boutique Hotel\r\n      Grand Hyatt Seoul', 'Remy Chalendard', '2026-03-03 11:04:27', '2026-03-03 11:04:27', 'images/itaewon.jpg', 'Quartiers', 'publie', NULL, 'publiée', NULL),
(11, 'Seoul, capital de la gastronomie', '', 'Séoul s\'impose comme une destination gastronomique de premier plan, où les saveurs du monde entier se côtoient dans une effervescence culinaire unique. La ville offre un éventail impressionnant d\'adresses, des tables traditionnelles coréennes aux restaurants fusion contemporains, en passant par une scène internationale particulièrement riche : japonais, chinois, italien, français, mexicain ou encore indien, tout y est représenté. Les classiques de la cuisine coréenne, comme le bibimbap, le bulgogi, le kimchi ou les jjigae, restent bien sûr incontournables.\r\n\r\nLa ville se distingue aussi par la coexistence de ses extrêmes culinaires. Dans les quartiers branchés de Gangnam ou d\'Itaewon, des restaurants gastronomiques proposent une cuisine soignée et créative. À l\'opposé, les marchés de rue de Gwangjang ou Myeongdong régalent les passants avec des spécialités accessibles comme les tteokbokki ou les hotteok, pour quelques milliers de wons seulement.\r\n\r\nCôté budget, Séoul sait s\'adapter à toutes les bourses. Les restaurants de quartier offrent des repas généreux à prix modestes, tandis que les expériences de fine dining peuvent représenter un investissement plus conséquent. Dans tous les cas, le rapport qualité-prix reste l\'un des points forts de la capitale coréenne, où chaque repas est une invitation à explorer une palette de saveurs aussi variée qu\'inattendue.\r\n', 'Remy Chalendard', '2026-03-03 12:38:39', '2026-03-04 10:35:48', 'images/photo-1761303506087-9788d0a98e87.webp', 'Restaurant', 'publie', NULL, 'publiée', NULL),
(12, 'Kimchi – Chou fermenté épicé, incontournable dans chaque repas.', '', 'Le kimchi est sans doute le plat le plus emblématique de la Corée du Sud. Préparé à base de légumes fermentés, le plus souvent du chou chinois ou du radis, il doit son caractère unique à un mélange savamment dosé de piments rouges, d\'ail, de gingembre et de sauce de poisson. La fermentation lui confère son goût légèrement acidulé si reconnaissable, ainsi que de nombreux bienfaits pour la santé, en particulier pour le système digestif.\r\n\r\nSa diversité est l\'une de ses grandes richesses : il existe des centaines de variantes selon les régions, les saisons et les familles. Concombre, navet, fruits de mer… les déclinaisons sont infinies, chacune apportant sa propre identité gustative. En Corée, le kimchi est présent à chaque repas, servi en petites portions parmi les banchan, ces accompagnements traditionnels qui garnissent systématiquement la table.\r\n\r\nMais le kimchi dépasse largement le cadre culinaire. Véritable symbole national, il est profondément ancré dans la culture et l\'histoire coréennes. Sa préparation collective, le kimjang, est un rituel familial et communautaire transmis de génération en génération, à tel point qu\'il a été inscrit au patrimoine culturel immatériel de l\'UNESCO. Goûteux, nutritif et chargé d\'histoire, le kimchi est bien plus qu\'un simple condiment : c\'est l\'âme de la cuisine coréenne.', 'Remy Chalendard', '2026-03-03 12:40:46', '2026-03-04 10:36:59', 'images/photo-1698489857683-0d30f7f046f7.webp', 'Restaurant', 'publie', NULL, 'publiée', NULL),
(13, 'Bibimbap - Le \"Riz Mélangé\"', '', 'Le bibimbap est un plat traditionnel coréen qui signifie littéralement riz mélangé. Il se compose d’un bol de riz blanc sur lequel sont disposés plusieurs légumes sautés ou marinés, comme les épinards, les carottes, les champignons et les germes de soja, ainsi qu’une source de protéines, souvent de la viande de bœuf ou un œuf.\r\nAvant de le déguster, on ajoute une sauce épicée sucrée à base de pâte de piment rouge, appelée gochujang, puis on mélange le tout pour obtenir un savoureux mélange de saveurs et de textures.\r\n\r\nLe bibimbap est non seulement délicieux, mais aussi très coloré et équilibré, offrant un contraste agréable entre le croquant des légumes, la tendreté de la viande et la douceur du riz. Une variante populaire est le dolsot bibimbap, servi dans un bol en pierre chaude qui rend le riz croustillant au fond. C’est un plat à la fois esthétique, nutritif et réconfortant, emblématique de la cuisine coréenne.', 'Remy Chalendard', '2026-03-03 12:42:21', '2026-03-03 12:42:21', 'images/istockphoto-183752521-612x612.webp', 'Restaurant', 'publie', NULL, 'publiée', NULL),
(14, 'Jungsik (정식당) - Cuisine coréenne moderne', '', 'Adresse : 11, Seolleung-ro 158-gil, Gangnam-gu, Séoul - (+82 2-517-4654)\r\n\r\nNiché au cœur du prestigieux quartier de Gangnam, Jungsik s\'est imposé comme l\'une des tables les plus respectées de la capitale coréenne. Couronné par des étoiles Michelin, ce restaurant gastronomique est reconnu comme un précurseur de la \"New Korean Cuisine\", un mouvement qui réinterprète avec audace et finesse les grands classiques de la cuisine traditionnelle coréenne.\r\n\r\nLa philosophie culinaire de Jungsik repose sur la valorisation des produits locaux et de saison, sublimés par des techniques contemporaines et un souci du détail poussé à l\'extrême. Chaque assiette y est pensée comme une œuvre à part entière, recherchant l\'équilibre parfait entre saveurs, textures et esthétique, tout en rendant hommage au patrimoine culinaire coréen.\r\n\r\nL\'expérience va bien au-delà de la simple dégustation : le cadre élégant et épuré, associé à un service attentionné et professionnel, plonge les convives dans une atmosphère raffinée où tradition et modernité se répondent en harmonie. Une adresse incontournable pour les amateurs de gastronomie en quête d\'une expérience mémorable à Séoul.\r\n\r\n', 'Remy Chalendard', '2026-03-03 12:45:44', '2026-03-04 10:38:18', 'images/DSC09557.webp', 'Restaurant', 'publie', NULL, 'publiée', NULL),
(15, 'Gaon (가온) - Cuisine coréenne traditionnelle', '', 'Adresse : 38, Dosan-daero 45-gil, Gangnam-gu, Séoul - (+82 2-815-3739)\r\n\r\nGaon figure parmi les restaurants les plus prestigieux de Séoul et de toute la Corée du Sud. Triplement étoilé au guide Michelin, cet établissement d\'exception s\'est forgé une réputation mondiale en portant la gastronomie coréenne traditionnelle à son plus haut niveau d\'expression. Chaque assiette y est une invitation à voyager à travers l\'histoire et le patrimoine culinaire du pays, sublimés par des ingrédients locaux soigneusement sélectionnés et des techniques d\'une grande précision.\r\n\r\nLa cuisine de Gaon se distingue par une attention particulière aux rythmes des saisons, qui dictent la composition des menus et guident le choix des produits. Les plats, d\'une élégance visuelle remarquable, jouent sur la complémentarité des textures, des couleurs et des arômes pour offrir une expérience sensorielle complète, où tradition et modernité se fondent en une harmonie naturelle.\r\n\r\nL\'atmosphère de Gaon est à l\'image de sa cuisine : sobre, raffinée et intimiste. Le service, discret et attentionné, accompagne chaque moment du repas avec professionnalisme, créant un cadre idéal pour une immersion totale dans ce que la gastronomie coréenne a de plus noble et de plus authentique. Une expércie rare, à vivre au moins une fois.\r\n\r\n    ', 'Remy chalendard', '2026-03-03 12:48:18', '2026-03-04 14:02:28', 'images/800_533_1074961.webp', 'Restaurant', 'publie', NULL, 'publiée', NULL),
(16, 'Mingles - Cuisine coréenne fusion', '', 'Adresse : 757, Dongho-ro, Jongno-gu, Séoul - (+82 2-515-7306)\r\n\r\nInstallé dans le quartier dynamique de Gangnam, Mingles s\'est imposé comme l\'une des adresses phares de la nouvelle scène gastronomique séoulite. Distingué par des étoiles Michelin, ce restaurant propose une vision singulière de la cuisine coréenne, où les saveurs et les techniques traditionnelles entrent en dialogue avec les influences et les codes de la gastronomie occidentale.\r\n\r\nLa philosophie de Mingles repose sur une sélection rigoureuse de produits locaux et de saison, travaillés avec précision et une créativité assumée. Chaque plat reflète cet équilibre subtil entre ancrage culturel et modernité culinaire : les recettes coréennes y sont réinterprétées avec audace, sans jamais trahir leur essence ni leur profondeur gustative.\r\n\r\nDans un cadre intimiste et soigneusement pensé, le restaurant cultive une atmosphère chaleureuse et sophistiquée. Le service, attentif et personnalisé, accompagne chaque étape du repas avec discrétion et bienveillance, faisant de chaque visite une expérience mémorable. Mingles est aujourd\'hui une référence incontournable pour quiconque souhaite explorer la gastronomie coréenne contemporaine dans toute sa richesse.\r\n\r\n', 'Remy Chalendard', '2026-03-03 12:50:39', '2026-03-04 10:41:09', 'images/mingles-439662.webp', 'Restaurant', 'publie', NULL, 'publiée', NULL),
(17, 'Tosokchon (토속촌)', '', 'Adresse : 5, Jahamun-ro 5-gil, Jongno-gu, Séoul - (+82 2-737-7444)\r\n\r\nTosokchon Samgyetang est l\'une des adresses les plus attachantes et les plus authentiques de Séoul. Niché dans une maison de style hanok au cœur de la capitale, le restaurant transporte ses convives dans une atmosphère d\'un autre temps, où le bois, les cours intérieures et l\'architecture traditionnelle coréenne créent un cadre chaleureux et dépaysant.\r\n\r\nLa maison est entièrement dédiée au samgyetang, cette soupe de poulet au ginseng considérée comme un véritable remède naturel dans la culture coréenne. Un poulet entier, farci de riz gluant, de ginseng, de jujubes et de châtaignes, mijote longuement dans un bouillon délicat et parfumé jusqu\'à obtenir une texture fondante et une saveur profonde. Simple en apparence, ce plat incarne à lui seul toute la philosophie de la cuisine médicinale coréenne, où nourrir le corps et prendre soin de sa santé ne font qu\'un.\r\n\r\nPlébiscité autant par les habitants du quartier que par les voyageurs venus des quatre coins du monde, Tosokchon est devenu bien plus qu\'un simple restaurant : c\'est une institution. Son service convivial et son cadre préservé en font une étape incontournable pour quiconque souhaite goûter à l\'un des plats les plus emblématiques du patrimoine gastronomique coréen.\r\n', 'Remy Chalendard', '2026-03-03 12:53:33', '2026-03-04 10:42:26', 'images/2018-05-25.webp', 'Restaurant', 'publie', NULL, 'publiée', NULL),
(18, 'La Yeon (라연) - Cuisine coréenne haut de gamme', '', 'Adresse : 35, Eulji-ro, Jung-gu, Séoul (Hôtel Shilla) - (+ 82 2-2230-3367)\r\n\r\nPerché au sommet de l’hôtel The Shilla Seoul, La Yeon est un restaurant gastronomique coréen d’exception, reconnu pour son élégance et son raffinement. Récompensé par trois étoiles Michelin, il offre une expérience culinaire unique où la tradition coréenne rencontre l’excellence de la haute gastronomie contemporaine.\r\n\r\nLa cuisine de La Yeon met à l’honneur les ingrédients saisonniers les plus nobles, sélectionnés avec soin à travers toute la Corée. Les plats, inspirés des recettes traditionnelles royales et familiales, sont revisités avec une précision moderne, révélant des saveurs subtiles, équilibrées et profondément authentiques. Chaque\r\nassiette est pensée comme une œuvre d’art, alliant esthétique, technique et respect du produit.\r\n\r\nDans un cadre luxueux et épuré, offrant une vue panoramique sur Séoul, La Yeon propose une expérience immersive où le service attentif et discret accompagne une cuisine d’une grande finesse. Véritable ambassadeur de la gastronomie coréenne haut de gamme, La Yeon s’adresse aux amateurs de cuisine d’exception en quête d’une\r\ndécouverte culturelle et sensorielle inoubliable.\r\n\r\nRestaurant gastronomique coréen triplement étoilé Michelin, situé au sommet de l’hôtel The Shilla Seoul.\r\n     \r\n- Cuisine raffinée inspirée des traditions coréennes, revisitée avec des techniques contemporaines.\r\n- Utilisation d’ingrédients saisonniers de haute qualité, soigneusement sélectionnés à travers la Corée.\r\n- Cadre élégant et épuré offrant une vue panoramique exceptionnelle sur la ville de Séoul.\r\n- Service haut de gamme, discret et attentif, garantissant une expérience culinaire d’exception.\r\n    \r\n\r\n', 'Remy Chalendard', '2026-03-03 12:56:12', '2026-03-03 12:56:12', 'images/7dc15a92-820f-4264-9d58-3260c8b58baa.webp', 'Restaurant', 'publie', NULL, 'publiée', NULL),
(19, 'Bicena - Cuisine coréenne moderne', '', 'Adresse : 27, Samseong-ro 85-gil, Gangnam-gu, Séoul - (+ 82 2-3213-1260)\r\n\r\nSitué au sein de l’hôtel Signiel Seoul, au sommet de la Lotte World Tower, Bicena est un restaurant gastronomique coréen qui propose une interprétation élégante et contemporaine de la cuisine traditionnelle. Dans un cadre moderne et lumineux, offrant une vue spectaculaire sur Séoul, le restaurant invite à une\r\nexpérience culinaire où raffinement et héritage culturel se rencontrent.\r\n\r\nLa cuisine de Bicena met en valeur les saveurs coréennes authentiques à travers des plats soigneusement élaborés à partir d’ingrédients de saison. Les recettes traditionnelles sont revisitées avec subtilité, en conservant l’équilibre naturel des goûts et une présentation soignée. L’expérience est complétée par un\r\nservice attentif et un environnement apaisant, idéal pour découvrir la gastronomie coréenne dans un cadre haut de gamme.\r\n\r\n- Restaurant gastronomique coréen situé au sommet de la Lotte World Tower, dans l’hôtel Signiel Seoul.\r\n- Cuisine traditionnelle coréenne revisitée avec une approche moderne et raffinée.\r\n- Utilisation d’ingrédients saisonniers soigneusement sélectionnés.</li>\r\n- Cadre élégant et contemporain avec une vue panoramique sur Séoul.</li>\r\n- Service professionnel et soigné, offrant une expérience culinaire haut de gamme.\r\n', 'Remy Chalendard', '2026-03-03 13:03:17', '2026-03-03 13:03:17', 'images/800_533_1074869.webp', 'Restaurant', 'publie', NULL, 'publiée', NULL),
(20, 'Séoul : Entre modernité et tradition', '', 'Séoul, la capitale de la Corée du Sud, est une métropole vibrante et dynamique où l\'histoire ancienne rencontre la modernité. Avec plus de 10 millions d\'habitants, elle est l\'une des plus grandes villes d\'Asie et un centre incontournable pour la culture, l\'innovation et l\'économie mondiale. Fondée il y a plus de 2000 ans sous le nom de « Hanseong », Séoul a su préserver son héritage tout en embrassant les défis de la modernité.\r\n\r\nVous y trouverez des palais majestueux comme le Gyeongbokgung, témoignant de la grandeur de la dynastie Joseon, mais aussi des gratte-ciel futuristes, des centres commerciaux ultramodernes et des technologies de pointe qui façonnent son quotidien.\r\n\r\nLa ville se distingue par une vie nocturne animée, avec ses rues bordées de néons et ses quartiers comme Gangnam, célèbres dans le monde entier notamment grâce au phénomène du « Gangnam Style ». Cependant, Séoul offre aussi de nombreux espaces verts, comme le parc de Namsan, ainsi que des montagnes environnantes qui invitent à l\'évasion.\r\n\r\nCôté gastronomie, Séoul est un véritable paradis pour les amateurs de cuisine. De la traditionnelle kimchi aux plats de barbecue coréen (« gogi-gui »), chaque repas est un voyage sensoriel. Les marchés comme Namdaemun ou Gwangjang ajoutent au charme de la ville, où l\'on peut savourer des spécialités locales dans une atmosphère authentique.', 'Remy Chalendard', '2026-03-03 13:13:32', '2026-03-03 15:19:39', 'images/index/seoulA (1).webp', 'Accueil', 'publie', NULL, 'publiée', NULL),
(22, 'Population et tourisme', '', 'Séoul, capitale de la Corée du Sud, compte environ 10 millions d\'habitants, mais son aire métropolitaine, incluant Incheon, atteint près de 27,6 millions de personnes, faisant de la ville la quatrième mégapole mondiale. Elle concentre à elle seule 50% de la population du pays.\r\n\r\nAprès l\'effondrement du tourisme pendant la pandémie (500 000 visiteurs en 2021), Séoul a retrouvé son dynamisme avec plus de 12 millions de visiteurs étrangers, proche des niveaux de 2019. Les attractions phares comme le palais de Gyeongbokgung, Myeongdong ou le village de Bukchon Hanok, ainsi que trois sites classés à l\'UNESCO, continuent d\'attirer les foules. La ville est également le berceau de la K-pop et du hallyu, qui renforcent son rayonnement mondial.\r\n\r\nCependant, cette densité exceptionnelle engendre des défis : embouteillages permanents, pression immobilière et tensions sur les ressources urbaines.\r\nEn 2026, Séoul reste une métropole incontournable, tiraillée entre préservation culturelle, attractivité touristique et défis infrastructurels, mais toujours au cœur de la vie économique et culturelle coréenne.', 'Remy Chalendard', '2026-03-03 13:20:49', '2026-03-04 08:59:46', 'images/index/yu-kato-q9rSwpv5mFk-unsplash (1).webp', 'Accueil', 'publie', NULL, 'publiée', NULL),
(23, 'Infrastructures', '', 'Séoul dispose de l’un des réseaux de transport les plus modernes, efficaces et accessibles au monde. La ville combine technologie, ponctualité et confort pour permettre des déplacements rapides aussi bien dans le centre urbain que vers les régions environnantes.\r\n\r\n1. Le métro de Séoul\r\nLe métro est l’élément central des transports à Séoul. Constitué de nombreuses lignes parfaitement interconnectées, il couvre quasiment toute l’agglomération. Les stations sont propres, bien signalées et équipées d’ascenseurs, d’écrans d’information en temps réel et de portes palières pour la sécurité. Les trains sont fréquents et les trajets restent très abordables. Le métro est également climatisé et dispose du Wi-Fi gratuit.\r\n\r\n2. Le réseau de bus\r\nLes bus complètent le métro et permettent d’atteindre des zones moins desservies. Le système est organisé par couleurs :\r\n\r\n- Bleu : longues distances entre grands axes\r\n\r\n- Vert : connexions entre quartiers et stations de métro\r\n\r\n- Jaune : circulation dans un même district\r\n\r\n- Rouge : bus interurbains reliant Séoul aux villes voisines. Les arrêts indiquent les horaires et les bus disposent généralement d’informations en anglais.\r\n\r\n3. Les taxis\r\nLes taxis sont nombreux, relativement abordables et disponibles 24h/24. On distingue les taxis standards (argentés ou blancs) et les taxis « deluxe » (noirs), plus confortables. La plupart acceptent la carte detransport T-money ou les paiements par carte bancaire.\r\n\r\n4. Les trains et la connexion interurbaine\r\nSéoul est reliée au reste du pays grâce à un réseau ferroviaire performant. Les trains KTX (à grande vitesse) permettent de rejoindre Busan, Daegu, Gwangju ou Daejeon en un temps record. Les gares majeures comme Seoul Station, Yongsan ou Cheongnyangni sont très modernes et bien connectées au métro.\r\n\r\n5. Les aéroports\r\nLa ville est desservie par deux aéroports :\r\n\r\nIncheon International Airport, l’un des plus réputés au monde, pour la majorité des vols internationaux.\r\n\r\nGimpo Airport, utilisé pour les vols domestiques et certaines liaisons régionales (Japon, Chine, etc.).\r\nLes deux aéroports sont facilement accessibles via métro, train express (AREX) ou bus limousine.\r\n\r\n6. Les modes de transport alternatifs\r\nSéoul propose également des vélos en libre-service (Seoul Bike Ddareungi), parfaits pour les trajets courts et pour explorer les pistes cyclables le long du fleuve Han. Les trotinettes électriques en libre-service sont aussi très répandues.', 'Remy Chalendard', '2026-03-03 13:25:34', '2026-03-03 13:31:18', 'images/2023-seoul-metro-map.webp', 'Accueil', 'publie', NULL, 'publiée', NULL),
(24, 'Manifestation des fans de Newjeans', '', 'Le Mardi 3 mars (heure coréenne), les fans de NewJeans, connus sous le nom de Bunnies, ont organisé une manifestation avec des camions publicitaires devant le siège social de HYBE. Ils exigeaient que HYBE et ADOR mettent fin à ce qu\'ils décrivaient comme un conflit prolongé et stérile, et garantissent le retour aux activités de groupe complètes pour les cinq membres : Minji, Hanni, Danielle, Haerin et Hyein.\r\nDans une déclaration, les fans ont cité une récente décision du tribunal du district central de Séoul, qui aurait statué qu\'il n\'existait aucun fondement valide pour résilier le contrat dans l\'affaire intentée par l\'ancienne PDG d\'ADOR, Min Hee Jin, désormais à la tête d\'ooak Records. Ils ont affirmé que « HYBE a aggravé le conflit en se basant sur de fausses allégations de reprise des droits de gestion ».\r\nLes fans ont également demandé au président de HYBE, Bang Si Hyuk, d\'assumer sa responsabilité dans cette situation et de résoudre le différend. Ils ont aussi pressé le PDG d\'ADOR, Lee Do Kyung, de retirer la plainte impliquant la famille de Danielle, de remplir son devoir de protection envers ses artistes, et de poursuivre légalement concernant les fuites de vidéos de surveillance étrangères et les reportages médiatiques.\r\nEn outre, les fans ont réclamé des excuses du PDG de Belift Lab, Kim Tae Ho, au sujet des accusations de plagiat d\'ILLIT envers NewJeans, ainsi que la suppression d\'une vidéo explicative qu\'ils accusent d\'avoir endommagé l\'identité unique de NewJeans.\r\nLes fans ont conclu en avertissant que si leurs demandes ne sont pas acceptées, ils mobiliseront « tous les moyens possibles » pour organiser une action collective plus massive.', 'Remy Chalendard', '2026-03-03 13:50:12', '2026-03-04 12:07:04', 'images/newjeanstruck.jpg', 'News', 'publie', NULL, 'publiée', NULL),
(25, 'Le Hangeul, une langue a porté de tous', '', 'Le Hangeul est l’alphabet coréen, qui à été créé au XVe siècle sous le règne du roi Sejong le Grand (1397‑1450). Avant sa création, les Coréens utilisaient principalement les caractères chinois (Hanja) pour écrire, ce qui rendait la lecture et l’écriture difficiles pour le peuple. En 1443, le roi Sejong et son équipe de savants ont inventé un alphabet simple et logique, composé de 14 consonnes et 10 voyelles de base, permettant de former toutes les syllabes coréennes. L’objectif du Hangeul était de démocratiser l’écriture, en offrant un système accessible à tous, même aux paysans illettrés. Chaque lettre est conçue pour refléter la forme des organes vocaux lors de la prononciation, ce qui rend l’apprentissage intuitif. Depuis sa création, le Hangeul est devenu un symbole de l’identité culturelle coréenne et est célébré chaque année le 9 octobre lors de la Journée du Hangeul en Corée du Sud.', 'Remy Chalendard', '2026-03-03 14:26:14', '2026-03-03 14:26:14', 'images/9229079-coreen-alphabet-lettres-hangeul-langue-vecteur-libre-telechargement-gratuit-vectoriel.jpg', 'Hangeul', 'publie', NULL, 'publiée', NULL),
(26, 'Les bus bleus', 'Ils relient les quartiers périphériques au centre-ville, il s\'agit de lignes longues et intermédiaires.', 'Les bus bleus de Séoul sont des lignes de transport interquartiers qui desservent\r\nprincipalement les zones périphériques de la ville. Ces lignes relient des quartiers plus éloignés et des banlieues à des zones centrales et importantes, notamment les grandes stations de métro, les quartiers d\'affaires et les zones commerciales. Les bus bleus sont idéaux pour ceux qui doivent parcourir des distances moyennes ou longues, mais ils restent très pratiques pour les déplacements quotidiens, grâce à leur capacité à se connecter à d’autres lignes de bus et aux réseaux de métro.\r\n\r\n- 100 : Relie Songpa (sud-est) à Dongdaemun (centre-ville).\r\n- 102 : Relie Gongdeok à Dongdaemun.\r\n- 105 : Relie Ilsan (nord-ouest de Séoul) à Jongno.\r\n- 1002 : Relie Gwangmyeong à Sinchon.\r\n- 104 : Relie Mapo à Myeongdong.\r\n- 105-1 : Relie Suwon à Gyeongnidan-gil.\r\n- 106 : Relie Sangbong à Hyehwa.\r\n- 107 : Relie Hangangjin à Dongdaemun.', 'Remy Chalendard', '2026-03-04 07:59:52', '2026-03-04 07:59:52', 'images/bleu.webp', 'Bus', 'publie', NULL, 'publiée', NULL),
(27, 'Les bus verts', 'Ils relient les stations de métro ou des arrêts de bus aux quartiers plus petits.', 'C\'est un réseau de bus local qui fait la navette entre des zones spécifiques.\r\n\r\nLes bus verts sont destinés à desservir des zones spécifiques et à faciliter les correspondances avec d\'autres lignes de bus ou le métro. Ce sont souvent des lignes locales qui relient des quartiers résidentiels ou des zones moins fréquentées avec des lignes de bus plus grandes ou des stations de métro.\r\n\r\n- 701 : Relie Gangdong à Jamsil.\r\n- 702 : Relie Junggye à Wangsimni.\r\n- 771 : Relie Yangjae à Jamsil.\r\n- 7025 : Relie Beomeo à Shindang.\r\n- 7013 : Relie Seongbuk à Jongno.\r\n- 703 : Relie Nowon à Sinsa.\r\n- 7734 : Relie Hongdae à Jamsil.\r\n- 744 : Relie Ogeum à Dongdaemun.', 'Remy Chalendard', '2026-03-04 08:02:15', '2026-03-04 08:02:15', 'images/vert.webp', 'Bus', 'publie', NULL, 'publiée', NULL),
(28, 'Les bus jaunes', '', 'Les bus de quartier desservent les zones résidentielles et les secteurs moins accessibles de la ville, assurant le lien entre les zones à faible densité et les grands axes de transport. Pensés pour des trajets courts et locaux, ils constituent un maillon essentiel du réseau en connectant les habitants de ces zones aux principales lignes de bus et aux stations de métro les plus proches, pour une mobilité du quotidien plus fluide et pratique.\r\n\r\n\r\n- 03 : Relie Cheongdam à Garak Market.\r\n- 06 : Relie Yangjae à Bangbae.\r\n- 13 : Relie Seongbuk à Gireum.\r\n- 15 : Relie Mapo à Shindang.\r\n- 23 : Relie Sinchon à Gupabal.\r\n- 25 : Relie Jamsil à Hanti.\r\n- 32 : Relie Daechi à Gongdeok.\r\n- 42 : Relie Gyeongnidan-gil à Oksu.', 'Remy Chalendard', '2026-03-04 08:04:05', '2026-03-04 10:17:48', 'images/jaune.webp', 'Bus', 'publie', NULL, 'publiée', NULL),
(29, 'Tarifs des bus à Séoul (2026)', 'Les tarifs peuvent légèrement varier en fonction du type de bus et du trajet. Voici les informations de base :', 'Tarif de base :\r\n\r\n- En bus bleu ou bus vert : 1 250 KRW (à partir de 2023) pour les trajets de base (jusqu\'à 10 km).\r\nEn bus rouge : 2 000 KRW (pour les trajets plus longs).\r\nEn bus jaune : 1 200 KRW (tarif similaire au bus bleu).\r\n\r\n- Tarif avec correspondance :\r\nSi vous prenez un bus et ensuite le métro, ou si vous changez de bus (dans un laps de temps de 30 minutes), vous bénéficiez d\'une réduction pour les correspondances.\r\nVous devez utiliser votre carte T-money pour que les correspondances soient automatiquement ajustées.\r\nRéductions :\r\n\r\n- Les enfants (jusqu\'à 6 ans) bénéficient de tarifs réduits ou gratuits dans certains cas.\r\nLes adultes peuvent également bénéficier de réductions, notamment pour les personnes âgées ou handicapées.', 'Remy Chalendard', '2026-03-04 08:06:04', '2026-03-04 12:07:04', 'images/T-Money.jpg', 'Bus', 'publie', NULL, 'publiée', NULL),
(30, 'Carte de transport (T-money et Climate Card)', 'Les cartes de transport', 'Le carte  de transport T-money et Climate Card sont les le moyen les plus pratique pour utiliser les transports en commun à Séoul (bus, métro et même les taxis). Vous pouvez charger de l’argent dessus (uniquement en espèce pour la climate Card) et les utiliser pour payer directement dans le bus ou le métro. Le tarif est déduit automatiquement selon la distance parcourue, l\'utilisateur doit cependant ne as oublier de valider sa carte lors de la descente du bus, sous peine de ce voir infliger le trajet complet de la ligne emprunter. ', 'Remy Chalendard', '2026-03-04 08:10:15', '2026-03-04 08:10:15', 'images/tmoney.webp', 'Bus', 'publie', NULL, 'publiée', NULL),
(31, 'Ligne 1', 'Couleur : Bleu foncé\r\nItinéraire: Nord – Sud, reliant le centre et la banlieue.', 'La ligne 1 du métro de Séoul est la plus ancienne et l\'une des plus emblématiques du réseau. Mise en service en 1974, elle traverse la ville du nord au sud et s\'étend bien au-delà du centre historique, reliant Séoul à de nombreuses villes de la banlieue. Plus qu\'une simple ligne urbaine, elle fonctionne comme un axe ferroviaire majeur, mêlant métro et trains de banlieue.\r\n\r\n- Seoul Station\r\n- Jonggak\r\n- Dongdaemun\r\n- Cheongnyangni', '', '2026-03-04 09:04:54', '2026-03-04 09:04:54', 'images/metro1.webp', 'Metro', 'publie', NULL, 'publiée', NULL),
(32, 'Ligne 2', 'Itinéraire : Ligne circulaire autour du centre-ville.\r\n', 'La ligne 2 du métro de Séoul est l\'une des plus emblématiques et des plus fréquentées du réseau. Reconnaissable à sa couleur verte, elle forme une grande boucle autour du centre-ville, reliant de nombreux quartiers clés et constituant un axe essentiel pour les déplacements quotidiens. Véritable cercle de vie urbaine, elle permet des correspondances avec presque toutes les autres lignes du métro.\r\n\r\nSon parcours traverse des zones parmi les plus dynamiques de la capitale, comme Hongdae, Sinchon, City Hall, Gangnam ou encore Jamsil. La ligne 2 relie ainsi des quartiers étudiants animés, des centres d\'affaires ultramodernes et des zones commerçantes majeures. En l\'empruntant, on perçoit les multiples visages de Séoul, entre culture, travail, loisirs et divertissement.\r\n\r\nLes stations de la ligne 2 sont modernes et très fonctionnelles, conçues pour absorber un flux constant de passagers. Les quais sont spacieux, bien éclairés et équipés de portes palières. Les rames, fréquentes et rapides, offrent un intérieur lumineux avec des écrans indiquant en temps réel les informations de trajet, ce qui rend les déplacements fluides malgré l\'affluence.\r\n\r\n- Hongik Univ.\r\n- City Hall\r\n- Gangnam\r\n- Jamsil', 'Remy Chalendard', '2026-03-04 09:08:38', '2026-03-04 09:08:38', 'images/metro2.webp', 'Metro', 'publie', NULL, 'publiée', NULL),
(33, 'Ligne 3', 'Couleur : Orange\r\nItinéraire : Nord-Ouest – Sud-Est.\r\n   ', 'La ligne 3 du métro de Séoul est un axe essentiel qui traverse la ville du nord-ouest au sud-est, reliant des quartiers résidentiels paisibles à des zones administratives et culturelles majeures. Identifiée par sa couleur orange, elle joue un rôle clé dans les déplacements quotidiens, notamment pour les habitants se rendant vers le centre de la capitale.\r\n\r\nSon tracé passe par des lieux emblématiques tels que Gyeongbokgung, Anguk ou encore Apgujeong, offrant un lien direct entre les quartiers historiques et les zones modernes et élégantes du sud de Séoul. En parcourant la ligne 3, on ressent un équilibre entre tradition et modernité : palais royaux, rues bordées de hanoks, mais aussi avenues larges et quartiers contemporains.\r\n\r\n- Gyeongbokgung\r\n- Anguk\r\n- Apgujeong\r\n- Express Bus Terminal', 'Remy Chalendard', '2026-03-04 09:12:41', '2026-03-04 09:12:41', 'images/metro3.webp', 'Metro', 'publie', NULL, 'publiée', NULL),
(34, 'Ligne 4', 'Couleur : Bleu clair\r\nItinéraire : Nord-Est – Sud.', 'La ligne 4 du métro de Séoul constitue un axe nord-sud incontournable de la capitale coréenne, traversant aussi bien des quartiers résidentiels animés que des zones commerciales et culturelles très prisées. Reconnaissable à sa couleur bleu clair, elle assure chaque jour la mobilité de milliers d\'habitants en reliant les secteurs du nord aux cœurs battants du centre et du sud de la ville.\r\n\r\nSon itinéraire dessert des sites phares tels que Dongdaemun, Myeongdong, Seoul Station ou Sadang, offrant un véritable voyage à travers les multiples facettes de Séoul : marchés animés, hauts lieux touristiques et quartiers plus tranquilles se succèdent au fil des stations. Ses nombreuses correspondances avec les autres lignes en font également un carrefour stratégique pour les déplacements dans toute la métropole.\r\n\r\nLes stations de la ligne 4, régulièrement entretenues et bien éclairées, sont conçues pour absorber un flux important de voyageurs grâce à des quais sécurisés et une signalétique intuitive. Les rames climatisées, qui se succèdent à intervalles rapprochés, garantissent des trajets fluides et efficaces, y compris lors des heures de pointe.\r\n', 'Remy Chalendard', '2026-03-04 09:16:12', '2026-03-04 10:02:11', 'images/metro4.webp', 'Metro', 'publie', NULL, 'publiée', NULL),
(35, 'Tarifs du métro à Séoul', 'Le paiement se fait principalement avec la carte T-money. Le tarif dépend de la distance parcourue.', 'Le métro de Séoul est l\'un des plus abordables au monde pour une capitale. En 2026, le tarif de base est de 1 500 wons (environ 1€) pour un trajet en carte T-money, contre 1 600 wons en paiement par ticket magnétique à usage unique.\r\nLe prix augmente en fonction de la distance parcourue. Une majoration de 100 wons est appliquée tous les 5 kilomètres supplémentaires jusqu\'à 10 km, puis tous les 10 kilomètres au-delà. Pour la grande majorité des trajets en centre-ville, le tarif de base suffit.\r\n\r\nLa carte T-money est fortement recommandée : rechargeable dans toutes les stations et dans de nombreuses conveniences stores, elle permet également de bénéficier de la correspondance gratuite entre le métro et le bus dans un délai de 30 minutes.\r\nDes tarifs réduits existent pour les enfants (450 wons), les adolescents (720 wons) et les personnes âgées de plus de 65 ans, qui bénéficient quant à eux de la gratuité totale sur l\'ensemble du réseau.\r\n\r\nIl est également possible d\'acheter des passes touristiques valables 1, 2 ou 3 jours, offrant un accès illimité au métro et aux bus pour respectivement 5 000, 8 000 et 10 000 wons. Ces passes sont disponibles à l\'aéroport et dans les principales stations touristiques.', NULL, '2026-03-04 09:19:19', '2026-03-04 12:07:04', 'images/T-Money.jpg', 'Metro', 'publie', NULL, 'publiée', NULL),
(36, 'Cartes de transport', 'Les cartes de transports T-Money ou Climate card', 'La carte T-money permet d’utiliser facilement le métro, les bus et même les taxis. Elle se recharge facilement et offre des réductions lors des correspondances. Elle est disponible à l\'achat dans les distributeurs des stations, ou dans les convenances stores (7Eleven, GS25)', 'Remy Chalendard', '2026-03-04 09:22:17', '2026-03-04 09:22:17', 'images/tmoney.webp', 'Metro', 'publie', NULL, 'publiée', NULL),
(37, 'Manifestation des fans de Newjeans\r\n', '', 'Le Mardi 3 mars (heure coréenne), les fans de NewJeans, connus sous le nom de Bunnies, ont organisé une manifestation avec des camions publicitaires devant le siège social de HYBE. Ils exigeaient que HYBE et ADOR mettent fin à ce qu\'ils décrivaient comme un conflit prolongé et stérile, et garantissent le retour aux activités de groupe complètes pour les cinq membres : Minji, Hanni, Danielle, Haerin et Hyein. Dans une déclaration, les fans ont cité une récente décision du tribunal du district central de Séoul, qui aurait statué qu\'il n\'existait aucun fondement valide pour résilier le contrat dans l\'affaire intentée par l\'ancienne PDG d\'ADOR, Min Hee Jin, désormais à la tête d\'ooak Records. Ils ont affirmé que « HYBE a aggravé le conflit en se basant sur de fausses allégations de reprise des droits de gestion ». Les fans ont également demandé au président de HYBE, Bang Si Hyuk, d\'assumer sa responsabilité dans cette situation et de résoudre le différend. Ils ont aussi pressé le PDG d\'ADOR, Lee Do Kyung, de retirer la plainte impliquant la famille de Danielle, de remplir son devoir de protection envers ses artistes, et de poursuivre légalement concernant les fuites de vidéos de surveillance étrangères et les reportages médiatiques. En outre, les fans ont réclamé des excuses du PDG de Belift Lab, Kim Tae Ho, au sujet des accusations de plagiat d\'ILLIT envers NewJeans, ainsi que la suppression d\'une vidéo explicative qu\'ils accusent d\'avoir endommagé l\'identité unique de NewJeans. Les fans ont conclu en avertissant que si leurs demandes ne sont pas acceptées, ils mobiliseront « tous les moyens possibles » pour organiser une action collective plus massive.', 'Remy Chalendard', '2026-03-04 12:21:19', '2026-03-04 12:21:19', 'images\\newjeanstruck.jpg', NULL, 'publie', NULL, 'publiée', NULL);
INSERT INTO `articles` (`id`, `titre`, `description`, `contenu`, `auteur`, `date_creation`, `date_modification`, `image`, `categorie`, `statut`, `user_id`, `etat`, `photo`) VALUES
(38, 'Les differentes lignes de métro de Seoul', '', 'Séoul dispose de l\'un des réseaux de métro les plus impressionnants au monde. Avec 9 lignes principales numérotées de 1 à 9, auxquelles s\'ajoutent plusieurs lignes secondaires, le métro dessert l\'ensemble de la ville ainsi que sa grande banlieue. Inauguré en 1974 avec la ligne 1, le réseau s\'est considérablement développé au fil des décennies pour atteindre aujourd\'hui plus de 300 stations. Réputé pour sa ponctualité, sa propreté et sa modernité, il est considéré comme l\'un des meilleurs systèmes de transport en commun au monde. Accessible grâce à la carte T-money, il permet de se déplacer facilement dans toute la métropole à un tarif abordable, faisant du métro le moyen de transport privilégié aussi bien des habitants que des touristes.\r\n\r\nLe métro de Séoul est également connu pour son confort et sa sécurité. Les rames sont modernes, climatisées et équipées de Wi-Fi gratuit, offrant une expérience agréable aux passagers. De plus, le réseau est bien entretenu et surveillé, garantissant la sécurité des usagers à tout moment. Les stations sont également dotées de nombreuses commodités, telles que des boutiques, des restaurants et des services de conciergerie, ce qui rend l\'expérience du métro encore plus agréable pour les voyageurs.\r\n\r\nEn plus de son efficacité, le métro de Séoul est également un symbole de la modernité et du dynamisme de la ville. Il joue un rôle crucial dans la vie quotidienne des Séouliens, facilitant les déplacements et contribuant à la réduction de la congestion routière. Que ce soit pour se rendre au travail, faire du shopping ou explorer les nombreux quartiers de la ville, le métro de Séoul est un moyen de transport incontournable pour tous ceux qui souhaitent découvrir cette métropole vibrante.', '', '2025-03-04 14:29:57', '2025-03-04 14:29:57', 'images/metro-de-Seoul.webp', 'Metro', 'publie', NULL, 'publiée', NULL),
(39, 'Newjeans, le feuilleton judiciaire qui a secoué le monde K‑pop', NULL, 'L’année 2026 marque un tournant majeur pour NewJeans, qui se retrouvent bien plus souvent dans les colonnes « faits d’actualité » que dans les charts pour le moment. Après des mois de bataille juridique contre leur label — la filiale HYBE/ADOR — la formation a connu de nombreux rebondissements.\r\n\r\n🧑‍⚖️ Le feuilleton judiciaire qui a secoué le monde K‑pop\r\n\r\nLa guerre entre NewJeans et ADOR, qui a commencé fin 2024, s’est prolongée tout au long de 2025 et 2026. Après que les membres ont tenté de rompre leur contrat, les tribunaux ont statué en faveur du label, confirmant que leur contrat exclusif est toujours valide.\r\n\r\nEntre‑temps, la chanteuse Danielle Marsh a vu son contrat résilié par ADOR fin décembre, ce qui a entraîné une procédure judiciaire à son encontre pour des dommages se chiffrant en dizaines de millions de dollars.\r\n\r\n🌍 Une formation fragmentée mais tournée vers l’avenir\r\n\r\nAlors que Danielle fait face à des poursuites et que d’autres membres se retrouvent séparés ou en négociation, trois membres — Hanni, Haerin et Hyein — ont été aperçus en répétition à Londres, alimentant des rumeurs sur une reprise d’activités possible en trio ou une restructuration du groupe.\r\n\r\nLe rôle de Minji, leader du groupe, reste incertain dans ce paysage en mutation, sa présence n’ayant pas encore été confirmée publiquement lors des dernières apparitions.\r\n\r\n📈 Toujours une immense influence musicale\r\n\r\nMême si leurs activités promotionnelles ont été limitées, NewJeans continue d’afficher une popularité phénoménale sur les plateformes de streaming. Leur single OMG a récemment dépassé les 900 millions d’écoutes sur Spotify, ajoutant une belle preuve de leur empreinte mondiale malgré l’absence de nouvelles sorties majeures en 2026.\r\n\r\n\r\n\r\n\r\n\r\n', NULL, '2026-03-05 17:37:21', '2026-03-08 18:42:55', 'images/nwjns1.jpg', 'News', 'publie', NULL, 'publiée', '69adbdf203692_nwjns1.jpg');

-- --------------------------------------------------------

--
-- Structure de la table `contact_messages`
--

CREATE TABLE `contact_messages` (
  `id` int NOT NULL,
  `nom` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `telephone` varchar(20) DEFAULT NULL,
  `sujet` varchar(255) NOT NULL,
  `message` longtext NOT NULL,
  `date_envoi` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `lu` tinyint(1) DEFAULT '0',
  `user_id` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- --------------------------------------------------------

--
-- Structure de la table `evenements`
--

CREATE TABLE `evenements` (
  `id` int NOT NULL,
  `titre` varchar(255) NOT NULL DEFAULT 'Sans titre',
  `lieu` varchar(255) NOT NULL,
  `date` date NOT NULL,
  `type` varchar(100) NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Déchargement des données de la table `evenements`
--

INSERT INTO `evenements` (`id`, `titre`, `lieu`, `date`, `type`, `created_at`, `user_id`) VALUES
(1, 'FC Seoul / Incheon', 'Seoul Stadium', '2026-03-08', 'Sport', '2026-03-02 15:05:57', NULL),
(2, 'Bunnies Camp', 'KSPO Stadium', '2026-03-09', 'Concert', '2026-03-02 15:05:57', NULL),
(3, 'Winter is coming', 'Lotte World ', '2026-03-10', 'Celebration', '2026-03-02 15:05:57', NULL),
(5, 'NEWJEANS', 'KOSPO DOME', '2026-04-15', 'Concert', '2026-03-03 08:27:32', NULL);

-- --------------------------------------------------------

--
-- Structure de la table `users`
--

CREATE TABLE `users` (
  `id` int NOT NULL,
  `name` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `password` varchar(255) NOT NULL,
  `role` enum('admin','user') DEFAULT 'user',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Déchargement des données de la table `users`
--

INSERT INTO `users` (`id`, `name`, `email`, `password`, `role`, `created_at`) VALUES
(1, 'Remy', 'chalendard.remy@gmail.com.com', 'hash...', 'admin', '2026-03-04 13:44:56'),
(2, 'Jean', 'jean@email.com', 'hash...', 'user', '2026-03-04 13:44:56');

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `admins`
--
ALTER TABLE `admins`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `username` (`username`),
  ADD UNIQUE KEY `user_id` (`user_id`);

--
-- Index pour la table `articles`
--
ALTER TABLE `articles`
  ADD PRIMARY KEY (`id`),
  ADD KEY `user_id` (`user_id`);

--
-- Index pour la table `contact_messages`
--
ALTER TABLE `contact_messages`
  ADD PRIMARY KEY (`id`),
  ADD KEY `idx_email` (`email`),
  ADD KEY `idx_date` (`date_envoi`),
  ADD KEY `user_id` (`user_id`);

--
-- Index pour la table `evenements`
--
ALTER TABLE `evenements`
  ADD PRIMARY KEY (`id`),
  ADD KEY `user_id` (`user_id`);

--
-- Index pour la table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `email` (`email`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `admins`
--
ALTER TABLE `admins`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT pour la table `articles`
--
ALTER TABLE `articles`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=40;

--
-- AUTO_INCREMENT pour la table `contact_messages`
--
ALTER TABLE `contact_messages`
  MODIFY `id` int NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT pour la table `evenements`
--
ALTER TABLE `evenements`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- AUTO_INCREMENT pour la table `users`
--
ALTER TABLE `users`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- Contraintes pour les tables déchargées
--

--
-- Contraintes pour la table `admins`
--
ALTER TABLE `admins`
  ADD CONSTRAINT `admins_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE;

--
-- Contraintes pour la table `articles`
--
ALTER TABLE `articles`
  ADD CONSTRAINT `articles_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);

--
-- Contraintes pour la table `contact_messages`
--
ALTER TABLE `contact_messages`
  ADD CONSTRAINT `contact_messages_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL;

--
-- Contraintes pour la table `evenements`
--
ALTER TABLE `evenements`
  ADD CONSTRAINT `evenements_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
